# Change these first
owner: smb # Your GitHub username
repo: mon-ip # Your GitHub repository name

# Add your sites here
sites:
  - name: Stefanie-Braun.de
    url: https://www.stefanie-braun.de
    maxResponseTime: 5000
  - name: Geschmacksache
    url: https://www.geschmacksache.online
    maxResponseTime: 5000
  - name: Fabula-Fantastica
    url: https://www.fabula-fantastica.online
    maxResponseTime: 5000
  - name: Fabula-Fantastica - SWTOR
    url: https://swtor.fabula-fantastica.online
    maxResponseTime: 5000
  - name: Fabula-Fantastica - MDZS
    url: https://mdzs.fabula-fantastica.online
    maxResponseTime: 5000

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.fabula-fantastica.online
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /mon-ip
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
